language: node_js
node_js: stable

cache:
  directories:
    - "node_modules"
    - "packages/d2-crud-plus-example/node_modules"

branches:
  only:
  - master

script:
  - cd packages/d2-crud-plus-example
  - npm install
  - npm run build:travis

before_install:
  - chmod 755 ./qshell
  - ./qshell account $AK $SK
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

after_success:
  - ./qshell qupload qiniu-config
  - ./qshell cdnrefresh -dirs cdnrefresh-dirs.txt
